spring:
  profiles:
    active: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最小连接数
      minimum-idle: 10
      #最大连接数
      maximum-pool-size: 20
springfox:
  documentation:
    swagger-ui:
      enabled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml