spring:
  profiles:
    active: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最小连接数
      minimum-idle: 10
      #最大连接数
      maximum-pool-size: 20
  rabbitmq:
    addresses: amqp://admin:123456@192.168.83.129:5672
    #开启消息确认PublisherConfirm，消息到达Exchange触发回调
    publisher-confirm-type: simple
    #当消息不能路由到队列中去的时候，会触发回调
    publisher-returns: true
    listener:
      direct:
        #消费者手动ACK
        acknowledge-mode: manual
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 100
        # 连接池最大空闲连接数
        max-idle: 50
        # 连接池最小空闲连接数
        min-idle: 8
    timeout: 10000ms

springfox:
  documentation:
    swagger-ui:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml